name: 'Fetch Issues by Version'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Next.js Version'
        required: true
        type: string

jobs:
  fetch_issues:
    if: github.repository_owner == 'vercel'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0

      - name: 'Fetch issues & send notification to Slack'
        run: node ./.github/actions/next-repo-actions/dist/issues-by-version/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
