name: 'Bankrupt issues'

on:
  workflow_dispatch:
    inputs:
      created:
        description: 'created date range'
        required: true
        type: string

jobs:
  bankrupt:
    if: github.repository_owner == 'vercel'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0

      - name: 'Bankrupt issues & send notification to Slack'
        run: node ./.github/actions/next-repo-actions/dist/bankrupt/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CREATED: ${{ github.event.inputs.created }}
